# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RSVP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RSVP
  pod 'Google/SignIn'
  pod 'Firebase/Auth'


  target 'RSVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RSVPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
